// Generated by packetc v0.1.4 at Sat, 16 Jan 2021 15:07:50 +0000
import { Reader, Writer } from "packet";
export interface Message {
    text: string,
}
export function read(reader: Reader, output: Message) {
    let output_text_len = reader.read_uint32();
    output.text = reader.read_string(output_text_len);
}
export function write(writer: Writer, input: Message) {
    writer.write_uint32(input.text.length);
    writer.write_string(input.text);
}
